### ISSUE TITLE
Frozen model not yet available

### ISSUE THREAD

**Issue by davidblumntcgeo** [DIUx-xView/baseline#2]
In your blog post you write, "As part of creating the DIUx xView dataset, we ran several baseline experiments and are releasing pre-trained weights along with frozen models for you to use. The motivation was to make sure competitors had a starting point to build from and to explore the dataset ourselves."

Could you please commit the frozen model?

**Comment by dariuslam** [comment]
Hi, please find the frozen model + pre-trained checkpoints here: https://github.com/DIUx-xView/baseline/releases
