### ISSUE TITLE
confirm tensorflow version?

### ISSUE THREAD

**Issue by vuptran** [DIUx-xView/baseline#7]
I'm using tf-cpu version 1.2.1 and getting `ValueError: No op named NonMaxSuppressionV2 in defined operations` when working with `create_detections.py` and the provided frozen models v1.1. The error may be related to tensorflow versioning. What is the version of tensorflow used to create the provided frozen models v1.0 and v1.1?

**Comment by dariuslam** [comment]
Hi, I am able to run the script without the error you describe using tensorflow-gpu 1.7.0.

A search of the error returned these similar issues: 
https://github.com/tensorflow/models/issues/3359
https://github.com/tensorflow/models/issues/3225
which point to an outdated TF version as cause of error.  I would suggest updating your tensorflow(-gpu).
